<!--
/**
 * Created By : Magebytes Pvt. Ltd.
 */
-->
<?php
$blockObj= $block->getLayout()->createBlock('Magebytes\ZipCodeValidator\Block\Product\View\Data');
$product = $blockObj->getCurrentProduct();
$isActive = $blockObj->getIsActive();
?>
<?php if($product && $isActive == 1): ?>
	<div class="zipchecker-product">
		<form class="zipcheck" method="post" id="zipcheck" novalidate="novalidate">
			<div class="zipcode-box">
				<div class="zipcode-inner">
					<div class="control">
						<input type="text" value="" placeholder="<?php echo __('Please Enter Delivery Zipcode') ?>" name="zipcode" id="zipcode" title="<?php echo __('Zipcode') ?>" class="input-text postcode valid" autocomplete="off" data-validate="{'required':true}">
					</div>
				</div>
				<div class="zipcode-check-btn">
					<button class="action primary" type="submit" title="Check" id="button-zipcheck">
						<span><?php echo __('Check') ?></span>
					</button>
				</div>
				<div class="message"></div>
			</div>
		</form>
	</div>
<script type="text/javascript">
require([
	'jquery',
	'mage/mage'
], function ($) { 
	var dataForm = $('#zipcheck');
	dataForm.mage('validation', {});
	var dataFormMessage = $('#zipcheck .message');
	dataFormMessage.removeClass('success').removeClass('error').hide();
	$('#button-zipcheck').on('click',function () {
		var formData = new FormData();
		formData.append('zipcode', $('#zipcheck input[name="zipcode"]').val());
		$.ajax({
			url: '<?php echo $this->getUrl('zipcodevalidator/index/index', ['id'=> $product->getId()]) ?>',
			data: formData,
			processData: false,
			contentType: false,
			showLoader: true,
			type: 'POST',
			dataType: 'json',
			success: function (response) {
				var resData = response.type;
				console.log(response);
				if (resData == 'success') {
					$('#product-addtocart-button').attr('disabled', false);

				}else{
					$('#product-addtocart-button').attr('disabled', true);
				}
				dataFormMessage.removeClass('success').removeClass('error').hide();
				dataFormMessage.addClass(response.type).html(response.message).show();
			}
		});
		return false;
	});
});
</script>
<?php endif; ?>